import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Header from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })
import Nav from '@/components/Nav'

export const metadata = {
  title: 'Annadata',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster position="bottom-center" toastOptions={{ duration: 4000 }} />
        <Header/>
        {/* <Nav/> */}
        <main className='w-full flex flex-col'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  
  )
}
