import { Inter } from 'next/font/google'
import '@/app/globals.css'
import AuthContextProvider from '@/context/AuthContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dash',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en" class="light">
      <body className={inter.className}>
        <AuthContextProvider>
          <main className='w-full flex flex-col'>
            {children}
          </main>
        </AuthContextProvider>
      </body>
    </html>

  )
}
